[장승진]구구단
campus-devil1032/campus-java-gugudan pull request #23
Opened 2023-05-02 08:12 UTC by jsj102

구구단 만들었습니다.
정수형 외에 입력받았을떄 그냥 터지는데 살리고 정상입력시까지 반복하게 하려면 어떻게 해야할까요?

2023-05-03 09:00 UTC, yshush approved these changes

2023-05-03 09:00 UTC, yshush commented on MyClassFunc.java
> +				if (min <= 999) {
이렇게 하시면 -값을 입력해도 넘어갈 것 같습니다, min에 1보다 크다는 조건도 추가해주시는게 좋을 것 같아요!

2023-05-03 09:16 UTC, jsj102 commented on MyClassFunc.java
> +				if (min <= 999) {
mvc로 나눠봤고 min != 0 대신 min >0조건으로 변경했습니다!

2023-05-03 16:56 UTC, ej31 requested changes

2023-05-03 16:56 UTC, ej31 commented on MyClassFunc.java
> +	public static class Controller {
클래스 명에는 그 역할을 포함시켜서 작명 시키는게 좋습니다!
기능이 추가 될 때 유연하게 대응이 되기 때문이고 더 중요한건 내가 코드 짤 때 그 흐름을 놓치지 않으려면 당장 눈앞에 보이는 변수명 함수명 클래스명이 도움을 줄 때가 가끔 있기 때문입니다.
다양한 이유가 있지만 그 중 가장 중요한건 기능의 의도가 코드에 제대로 표현 되어야 유지보수가 가능하다는 점입니다 🐤

2023-05-03 16:56 UTC, ej31 commented on MyClassFunc.java
> +	public static class Model {
이너 클래스보다 외부로 파일을 따로 빼서 만들어 보시는건 어떨까요?~
MVC 모델은 결국 관심사 분리를 반영하기 위한 디자인 모델이라 클래스들끼리 서로 친하지 않게 만들어 주시는게 좋습니다 :)

2023-05-03 16:56 UTC, ej31 commented on MyClassFunc.java
> +	public static class Model {
음 친하지 않다는건 전부 개별적인 파일로 나눠놓는게 좋고 의존의 방향을 가급적 단방향으로 가져가는게 좋다는 의미입니다.
(순환참조를 방지 할 수 있어서..)
화이팅 👍

2023-05-03 16:56 UTC, ej31 commented on MyClassFunc.java
> +					this.scannumber = sca.next();
this.scannumber의 경우 지금 loop block 안에서만 사용되고 있는 상태이고 다른 클래스 내 메서드에서 쓰이는 경우가 없으므로 String 타입으로 따로 선언해서 내부 로컬 변수로 쓰시는게 좋습니다 👍

2023-05-03 16:56 UTC, ej31 commented on MyClassFunc.java
> +		public boolean isInteger(String s) {
클래스 내부에서만 쓰는 함수는 private 으로 접근 제한하시는게 좋습니다.
다른 개발자가 접근 할 필요가없는 메서드에 접근을 하기 시작하면 나중에 코드 리팩터링 할 때 곤란 할 때가 있습니다.

모든 코드는 시간이 지날 수록 혼잡도가 증가 할 수 밖에 없는 성질이 있는데요, 이를 낮추기 위해서라도 접근이 불필요한 메서드 혹은 변수는 전부 감춰두는게 좋습니다.

2023-05-03 16:56 UTC, ej31 commented on MyClassFunc.java
> +	public static class View {
클래스명,함수명,변수명에는 그 역할과 의도를 꼭 반영하기!

2023-05-04 04:58 UTC, jsj102 commented
다중계산이 가능하지만 연산자 우선순위에 상관없이 무조건 앞에서부터 차례로 계산하는 오류가 있습니다.  어떤식으로 수정하는게 좋을까요? 리뷰 받은내용도 어느정도 반영해보았는데 맞게한건지 모르겠습니다.

2023-05-09 02:37 UTC, jsj102 commented
연산자 우선순위 +-*/에 대해 처리가 가능하도록 수정하였으나 음수를 계산식으로 받아 계산할수 없습니다.
public의 경우 method외에 쓸일이 없어 method에서만 사용하였고,
대부분의 내부 변수에 private를 사용하였습니다.

2023-05-09 07:46 UTC, jsj102 commented
연산자 우선순위 +-*/에 대해 처리가 가능하도록 수정하였으나 음수를 계산식으로 받아 계산할수 없습니다.
public의 경우 method외에 쓸일이 없어 method에서만 사용하였고,
대부분의 내부 변수에 private를 사용하였습니다.
연속된 계산식에 대한 처리가 가능합니다.
예시는 10*10*10= / 5+10*3*10*3+5-1*1= 등입니다.
(-1)에 해당하는 음수처리는 지원하지 않습니다.
끝내고 난뒤에 생각해보니 그냥 조금 번거롭더라도 substring을 사용하여 계산식을 하나씩 줄여가는 방식이 확장성면이나 코드 가독성부분에서 더 낫지않았을까 생각합니다.

2025-07-09 07:02 UTC, closed without merging