[윤소영] 구구단 과
campus-devil1032/campus-java-gugudan pull request #36
Opened 2023-05-02 08:39 UTC by yun923

2023-05-03 06:35 UTC, ggyujin commented
잘하셨습니다! 👍

2023-05-04 02:36 UTC, campus-devil1032 requested changes

2023-05-04 02:36 UTC, campus-devil1032 commented on 윤소영/myFirstClass.java
> +		Integer num = 0;
Integer의 경우 기본타입과 사용 용도가 조금 다른면이 있습니다.
단순히 값만 저장하실 경우 int 를 사용하시는게 좋을 수 있습니다.
Integer는 뒤에서 배울 컬렉션을 사용 할 때 쓰이게 됩니다.

컬렉션에 데이터를 넣을때는 원시자료형 (=기본자료형)을 그대로 넣을수 없기 때문에..

하지만 만약! 함수에서 인자로 받는 값이 0이 아닌 null을 받아야 하는 상황이라면 Integer를 사용 할 수도 있는점 참고해주세요!

2023-05-04 02:36 UTC, campus-devil1032 commented on 윤소영/myFirstClass.java
> +
`while(true)` 를 통해서 사용자가 종료 명령을 내리기 전까지는 계속 작동하는 프로그램 형태로 한번 만들어보세요!

2023-05-04 02:36 UTC, campus-devil1032 commented on 윤소영/myFirstClass.java
> +		if ((num <= 0) || (num > 999)) {
계산 로직 혹은 조건이 적시 되어 있는 경우 그 의도와 결과를 주석으로 설명해두시는게 유지보수에 도움이 될 수 있습니다.
괄호는 한 꺼풀 정리해도 괜찮습니다.~
```
        if ((num <= 0) || (num > 999)) {} ...
// 위와 아래는 결과값이 동일
        if (num <= 0 || num > 999) {} ...
```

2023-05-04 02:36 UTC, campus-devil1032 commented on 윤소영/myFirstClass.java
> +		}catch(MyException e) {
Exception 클래스 이름은 발생한 상황에 대해서 최대한 명시적으로 적시해주시는게 좋습니다!

2023-05-04 02:36 UTC, campus-devil1032 commented on 윤소영/myFirstClass.java
> +			}
이런 계산로직에는 기능과 결과 값 등을 주석으로 적어놓는게 유지보수에 도움이 됩니다~

2023-05-04 02:36 UTC, campus-devil1032 commented on 윤소영/myFirstClass.java
> +	}
생성자가 비어있다면 생략해도 괜찮습니다
Exception 클래스와 RuntimeException 클래스의 사용상의 차이점과 Error vs Exception의 비교도 한번 공부해보세요!

2023-05-10 05:52 UTC, closed without merging